# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 1
sudo: false
language: node_js
node_js:
 - '8'
 - '6'
 - '4'
env:
  global:
    - NO_UPDATE_NOTIFIER=1

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - npm config set loglevel warn
  - npm i -g npm@latest-5

install: yarn --frozen-lockfile

before_script:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

script: yarn run ci

notifications:
  slack: lernajs:qHyrojRoqBBu7OhDyX1OMiHQ
